# Generated by Django 4.2.13 on 2024-07-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_naveruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('development_period', models.CharField(choices=[('0-3', '0~3개월'), ('4-7', '4~7개월'), ('8-11', '8~11개월'), ('12+', '12개월 이상')], max_length=5)),
                ('participants', models.CharField(choices=[('1-6', '1~6명'), ('7-12', '7~12명'), ('13-18', '13~18명'), ('19+', '19명 이상')], max_length=6)),
                ('language', models.CharField(choices=[('python', 'Python'), ('numpy', 'Numpy'), ('pandas', 'Pandas'), ('java', 'Java'), ('javascript', 'JavaScript'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('c++', 'C++'), ('other', '직접입력')], max_length=10)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
