# Generated by Django 4.2.13 on 2024-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_boardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
